# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hakuban < Formula
  desc "A terminal whiteboard where moving a card runs the automation you declared."
  homepage "https://wagnerlim.github.io/hakuban/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.0/hakuban_0.1.0_darwin_amd64.tar.gz"
      sha256 "d829aaec7eb25e66281f086c787626eb53e0fb8414fcebad102351fb66f610c1"

      define_method(:install) do
        bin.install "hakuban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.0/hakuban_0.1.0_darwin_arm64.tar.gz"
      sha256 "a45c644bbc48532680d0099a5f42c5ea2ade91651f83fa42515f8940b75a4a41"

      define_method(:install) do
        bin.install "hakuban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.0/hakuban_0.1.0_linux_amd64.tar.gz"
      sha256 "d200363512fe6a559da15beebddedd9eb89b43adcae805c2f6ec8c81c124207a"
      define_method(:install) do
        bin.install "hakuban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.0/hakuban_0.1.0_linux_arm64.tar.gz"
      sha256 "20172ceb0447a87729a3baaa571cd2a277a1cb4a28b7acf7d063d0fbfc611622"
      define_method(:install) do
        bin.install "hakuban"
      end
    end
  end

  test do
    system "#{bin}/hakuban", "version"
  end
end
