# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hakuban < Formula
  desc "A terminal whiteboard where moving a card runs the automation you declared."
  homepage "https://wagnerlim.github.io/hakuban/"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.2/hakuban_0.1.2_darwin_amd64.tar.gz"
      sha256 "cd2c0fe80d31e38fca7bc02cb7cff3c5c0fec68a43efb3d2be07f23c519d6175"

      define_method(:install) do
        bin.install "hakuban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.2/hakuban_0.1.2_darwin_arm64.tar.gz"
      sha256 "35bcd9b8fa7e73cb9267698cf135f61362599aef266af62b0c2d8b658a2f6ba9"

      define_method(:install) do
        bin.install "hakuban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.2/hakuban_0.1.2_linux_amd64.tar.gz"
      sha256 "9c4957d131ba530afea633ec480dc6b9c7de8837d0ad3015405ca501f2bb371d"
      define_method(:install) do
        bin.install "hakuban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.2/hakuban_0.1.2_linux_arm64.tar.gz"
      sha256 "2539d8b435304a42a94103429ee00514c1b7c437b2d4ce8838f8b14494dd6f6e"
      define_method(:install) do
        bin.install "hakuban"
      end
    end
  end

  test do
    system "#{bin}/hakuban", "version"
  end
end
