# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hakuban < Formula
  desc "A terminal whiteboard where moving a card runs the automation you declared."
  homepage "https://wagnerlim.github.io/hakuban/"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.1/hakuban_0.1.1_darwin_amd64.tar.gz"
      sha256 "3c2971558904a74ff4073dfdc08e0163c907a4dd96d23d0959f620924fade959"

      define_method(:install) do
        bin.install "hakuban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.1/hakuban_0.1.1_darwin_arm64.tar.gz"
      sha256 "907524d26fab6e893b5ee0ed99ab401dcb595d011db3926758d8a2659e72024c"

      define_method(:install) do
        bin.install "hakuban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.1/hakuban_0.1.1_linux_amd64.tar.gz"
      sha256 "a94d52f7834a5c01f4fe2f73628056e41a6d13dff29d2c98b8bfde60f5bf731a"
      define_method(:install) do
        bin.install "hakuban"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wagnerlim/hakuban/releases/download/v0.1.1/hakuban_0.1.1_linux_arm64.tar.gz"
      sha256 "27d4ec807681e6d2404cb73f669d223bf36d0ebbc4cc2499345bc025b409c98f"
      define_method(:install) do
        bin.install "hakuban"
      end
    end
  end

  test do
    system "#{bin}/hakuban", "version"
  end
end
